# Generated by Django 5.0.6 on 2024-06-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineNumber', models.TextField(verbose_name='№ машины')),
                ('engineNumber', models.TextField(verbose_name='№ двигателя')),
                ('transmissionNumber', models.TextField(verbose_name='№ трансмиссии')),
                ('driveAxleNumber', models.TextField(verbose_name='№ Ведущего моста')),
                ('steeringAxleNumber', models.TextField(verbose_name='№ управляемого моста')),
                ('deliveryContract_N_data', models.TextField(verbose_name='Договор поставки №, дата')),
                ('deliveryDate', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(verbose_name='Грузополучатель (конечный потребитель)')),
                ('deliveryAdress', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('completeSet', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.client', verbose_name='Клиент')),
                ('driveAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.driveaxlemodel', verbose_name='Модель ведущего моста')),
                ('engineModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.enginemodel', verbose_name='Модель двигателя')),
                ('machineModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.machinemodel', verbose_name='Модель техники')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.role')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.role'),
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.role')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureDate', models.DateField(verbose_name='Дата отказа')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('failureDescription', models.TextField(verbose_name='Описание отказа')),
                ('usedSpareParts', models.TextField(verbose_name='Используемые запасные части')),
                ('repairDate', models.DateField(verbose_name='Дата восстановления')),
                ('machineDowntime', models.IntegerField(verbose_name='Время простоя техники')),
                ('failureNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.failurenode', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.machine', verbose_name='Mашина')),
                ('repairMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.repairmethod', verbose_name='Способ восстановления')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.servicecompany', verbose_name='Cервисная компания')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steeringAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicalServiceDate', models.DateField(verbose_name='Дата проведения ТО')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('orderNumber', models.TextField(verbose_name='№ заказ-наряда')),
                ('orderDate', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.machine', verbose_name='Машина')),
                ('technicalServiceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.servicecompany', verbose_name='Организация, проводившая ТО')),
                ('technicalServiceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.technicalservicetype', verbose_name='Вид ТО')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='transmissionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasilant.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
