# Generated by Django 5.0.6 on 2024-06-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_checkrole'),
        ('datasilant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecompany',
            name='role',
        ),
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
